name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: wakatime
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          IGNORED_LANGUAGES: YAML JSON TOML MARKDOWN HTML JAVASCRIPT
          CODE_LANG: typescript
          TIME_RANGE: all_time
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 5
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
